### ISSUE TITLE
Internet access required for UI

### ISSUE THREAD

**Issue by dciuenciece2** [FreeTAKTeam/UI#11]
When connecting to the UI the browser reaches out to multiple domains. If you have no internet connection (likely scenario) then these calls will hang then fail rendering the UI unworkable in this scenario.

The domains are:

https://cdn.jsdelivr.net/npm/apexcharts
https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800
https://use.fontawesome.com/releases/v5.0.6/css/all.css
https://cdn.socket.io/socket.io-1.4.5.js

**Comment by Cale-Torino** [comment]
Perhaps All those files will be included in the next release for offline calling? Or you can add them and submit a pull request.

**Comment by Cale-Torino** [comment]
Looks like it was done  here: https://github.com/FreeTAKTeam/UI/pull/13

**Comment by brothercorvo** [comment]
Closed
