### ISSUE TITLE
[Bug] FreeTAKServer register page bugs

### ISSUE THREAD

**Issue by Cale-Torino** [FreeTAKTeam/UI#14]
Hi,
I noticed a small bug where when the exception for a user which exists is triggered the left navigation drawer menu is exposed with clickable buttons.

Also when attempting to create an account on the `FreeTAKServer `, clicking the register button presents what looks like a SQL error. See the images below:

User exists bug:

![113354798-fe15db00-933f-11eb-9d4a-ffe4723a5f87](https://user-images.githubusercontent.com/52330180/113479153-9b325a00-948d-11eb-8e1f-fc283fb79d48.gif)

Create an account error:

![113354812-040bbc00-9340-11eb-9a8c-146bfb6d0faa](https://user-images.githubusercontent.com/52330180/113479158-9f5e7780-948d-11eb-8c42-dfc35b95252d.png)

**Comment by naman108** [comment]
register button has been removed
