### ISSUE TITLE
UI unable to Connect FTAK Server

### ISSUE THREAD

**Issue by aaron1uk** [FreeTAKTeam/UI#20]
Yesterday I was experimenting with Free TAK Server in AWS, I currently have it setup so it accessed by it's public IP, I have  setup the correct security group rules evidenced by the fact that I am able to connect from my Andriod Device App. The problem is with the UI, I am able to accesses and login with the default admin credentials however UI App is unable to communicate with the FTAK server. 

Firefox Console reports a CORS issue, Chrome Console reports Connection Refused.

Just to be clear apps are running on same server and I used the first start wizard to setup.

I have experimented with the config.py currently I have:

```
# this IP will be used to connect with the FTS API
IP = 'Set as local IP Server is FTAK Running on'
# the public IP your server is exposing
APPIP = '0.0.0.0'
```
I think this may be the problem, where I have tried to set APPIP to the public IP I am using however I am unable to as I am unable to start the UI as I receive the following error:
```
File "/usr/local/lib/python3.8/dist-packages/FreeTAKServer-UI/run.py", line 107, in <module>
    wsgi.server(sock = eventlet.listen((app_config.APPIP, app_config.APPPort)), site=app)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/convenience.py", line 78, in listen
    sock.bind(addr)
OSError: [Errno 99] Cannot assign requested address
```
I'm hoping this is a bug and I've not missed something vital in the Documentation.

**Comment by mattloretitsch-od** [comment]
Update on what I have found so far.  If you watch all of the network connections from your browser, you can see the problem.  It's trying to open a socket to the private 10.xxx address of my vm in Azure.

GET | http://10.2.0.4:19023/socket.io/?EIO=3&transport=polling&t=NnwPwfc
