### ISSUE TITLE
Release 1.9.8 reports the wrong version.  It has 1.9.5 built in.

### ISSUE THREAD

**Issue by deddc23efb** [FreeTAKTeam/UI#23]
grep - r 1.9.5  UI-1.9.8/*
...
UI-1.9.8/FreeTAKServer-UI/app/__init__.py:    app.config['UIVERSION'] = '1.9.5'
Binary file UI-1.9.8/FreeTAKServer-UI/tests/chromedriver matches
UI-1.9.8/setup.py:    version='1.9.5',

The web application displays the incorrect version on the about screen as well.

[UI SERVER INFO]
Version 1.9.5
192.168.2.124:5000

Comments in the app/init.py file imply that the 1.9.5 is actually a database version number.  It's very confusing to have the DB version displayed as the web UI code version - it seems like it's not right.

**Comment by brothercorvo** [comment]
solved in 1.9.8
