### ISSUE TITLE
Port Forwarding option for UI

### ISSUE THREAD

**Issue by Marshmellow84** [FreeTAKTeam/UI#35]
How can we adjust the port for the UI so we can access its fully use off the main system?

I would like to add/remove users from my connection on let's say my cellphone durning times I'm not near my machine. And add/remove data packages on the Mission Screen.

Or if there is already a solution please advise.

As it stands this is basically a Read-Only access.

Thank you

**Comment by brothercorvo** [comment]
Not sure what is your issue here. Yes you can adjust the UI port 
follow the instructions to change the port here:
https://freetakteam.github.io/FreeTAKServer-User-Docs/Installation/Linux/1_Install/

your real issue seems to be that your UI runs behind NAT and you need to port forward in the router

**Comment by brothercorvo** [comment]
closing this because no further input
