### ISSUE TITLE
Unable to Add or Delete files on Mission Page

### ISSUE THREAD

**Issue by themanbornwithin** [FreeTAKTeam/UI#55]
FTS 2.1 RC1, UI 2.1

Clean install from ZTI. I am unable to add or delete files under the Data Package section. I can select a file to upload, but errors out saying 'Add Datapackage failed. Contact administrator'. If I try to delete a file, it says successful but the file remains.

**Comment by brothercorvo** [comment]
@naman108 it looks like this is a secondary effect of the Enterprise Sync implementation

**Comment by naman108** [comment]
This is addressed by the most recent FTS Release https://github.com/FreeTAKTeam/FreeTakServer/releases/tag/v2.1.01
