### ISSUE TITLE
Data Package text bug

### ISSUE THREAD

**Issue by Calcyn19** [FreeTAKTeam/UI#57]
I have a text bug on a fresh installation.

![image](https://github.com/FreeTAKTeam/UI/assets/155567592/8ba731b7-91ef-4a4d-ac6a-da3683281184)

Package 1 is generated by the UI (created a FTSUser package to give right to access SSL)
Package 2 is uploaded from ATAK 
As you can see, the name is unintelligible on the UI.
If i want to redownload the package from the server, the name is correctly written on the interface. 

Support : Raspberry Pi 5 8Go
OS : Raspberry Pi OS (64-bit) / Debian Linux 12
Python: 3.11
FTS version : 2.1

Installation of FTServer was done following : https://freetakteam.github.io/FreeTAKServer-User-Docs/Installation/Linux/Service/
No customs modifications. Pip check FreeTAKServer resulted in "No broken requirements found."

**Comment by brothercorvo** [comment]
this is a small cosmetic issue with the CSS, the name is correct.

**Comment by Calcyn19** [comment]
If it can help : 
![image](https://github.com/FreeTAKTeam/UI/assets/155567592/cb30bad1-eda3-47b4-9ff7-8f94bf551753)

Generated name Certs in User Group is also weird.

And yes it does work as intended otherwise

**Comment by brothercorvo** [comment]
fixed

> If it can help : ![image](https://private-user-images.githubusercontent.com/155567592/293981753-cb30bad1-eda3-47b4-9ff7-8f94bf551753.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMDQ0MjEsIm5iZiI6MTcwNDMwNDEyMSwicGF0aCI6Ii8xNTU1Njc1OTIvMjkzOTgxNzUzLWNiMzBiYWQxLWVkYTMtNDdiNC05ZmY3LThmOTRiZjU1MTc1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QxNzQ4NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2U4MzUwNTA1MGI3NzE3NzYzNDc4NTg5YjVmNWFkMTMyZjIyNTM4YjRkMTMwMTg3OGZkNjQxNjFiOWM1YTdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-SozbuiUtB08fcgFAQtQxvS1-oSLnV-Uw9FNQzb5syE)
> 
> Generated name Certs in User Group is also weird.
> 
> And yes it does work as intended otherwise
this is how is supposed to be.
closing this will be in the next release
