### ISSUE TITLE
Provide specific HTML for common mis-configuration 

### ISSUE THREAD

**Issue by phreed** [FreeTAKTeam/UI#60]
“This has been explained many times before: you have the wrong IP in your configuration. Now if you don't know what an internal IP is the easiest way is to use a digital ocean install. In other case, read this forum and the docs.”

<img width="1312" alt="image" src="https://github.com/FreeTAKTeam/UI/assets/211644/ed9ac75c-0023-4277-94fe-92f427585dfc">

The message should be brief and provide a stable link into the documentation.

**Comment by naman108** [comment]
Working on this now in linked branch
